CREATE DATABASE SAMPLE21;
USE SAMPLE21;

CREATE TABLE EMPLOYEES(
	EMP_ID INT PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    DEPARTMENT VARCHAR(20) NOT NULL,
    SALARY INT NOT NULL,
    AGE INT NOT NULL,
    GENDER ENUM("M","F","O")
);
INSERT INTO employees (emp_id, name, department, salary, age, gender) VALUES
(1, 'Alice',  'HR',    50000, 28, 'F'),
(2, 'Bob',    'IT',    70000, 32, 'M'),
(3, 'Carol',  'IT',    72000, 30, 'F'),
(4, 'David',  'HR',    52000, 45, 'M'),
(5, 'Eva',    'Sales', 60000, 29, 'F'),
(6, 'Frank',  'Sales', 58000, 35, 'M');
SELECT * FROM EMPLOYEES;

SELECT SUM(SALARY) FROM EMPLOYEES;
SELECT SUM(SALARY) FROM EMPLOYEES
WHERE GENDER = "F";
SELECT SUM(SALARY) FROM EMPLOYEES
WHERE AGE < 35;
SELECT SUM(SALARY) FROM EMPLOYEES
WHERE DEPARTMENT = "IT"; 

SELECT COUNT(*) FROM EMPLOYEES;
SELECT COUNT(*) FROM EMPLOYEES
WHERE DEPARTMENT = "SALES";
SELECT COUNT(*) FROM EMPLOYEES
WHERE SALARY > 60000;
SELECT COUNT(*) FROM EMPLOYEES
WHERE AGE > 30 AND GENDER="M";
 
SELECT MIN(SALARY) FROM EMPLOYEES;
SELECT MIN(AGE) FROM EMPLOYEES
WHERE GENDER = "F";
SELECT MIN(SALARY) FROM EMPLOYEES
WHERE DEPARTMENT = "IT";
SELECT MIN(SALARY) FROM EMPLOYEES
WHERE SALARY > 55000; 


SELECT MAX(SALARY) FROM EMPLOYEES;
SELECT MAX(AGE) FROM EMPLOYEES
WHERE DEPARTMENT = "SALES";
SELECT MAX(SALARY) FROM EMPLOYEES
WHERE GENDER = "M";
SELECT MAX(SALARY) FROM EMPLOYEES
WHERE AGE < 35; 

SELECT AVG(SALARY) FROM EMPLOYEES;
SELECT AVG(SALARY) FROM EMPLOYEES
WHERE AGE > 30;
SELECT AVG(SALARY) FROM EMPLOYEES
WHERE DEPARTMENT = "HR";
SELECT AVG(SALARY) FROM EMPLOYEES
WHERE GENDER = "F"; 

SELECT * FROM EMPLOYEES;



CREATE TABLE ORDERS(
	ORDER_ID INT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(20) NOT NULL,
    PRODUCT VARCHAR(20) NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 1,
    PRICE INT NOT NULL DEFAULT 0,
    CITY VARCHAR(20) NOT NULL
);
INSERT INTO orders (order_id, customer_name, product, quantity, price, city) VALUES
(1, 'John',   'Laptop',     1, 75000, 'Mumbai'),
(2, 'Alice',  'Smartphone', 2, 30000, 'Delhi'),
(3, 'Bob',    'Laptop',     1, 74000, 'Bangalore'),
(4, 'Diana',  'Tablet',     3, 25000, 'Mumbai'),
(5, 'Chris',  'Smartphone', 1, 31000, 'Chennai'),
(6, 'Eva',    'Laptop',     2, 76000, 'Delhi'),
(7, 'Frank',  'Tablet',     1, 26000, 'Mumbai');
SELECT * FROM ORDERS;

SELECT PRODUCT,SUM(QUANTITY) FROM ORDERS
GROUP BY PRODUCT;
SELECT CITY,COUNT(*) FROM ORDERS
GROUP BY CITY;
SELECT PRODUCT,MIN(PRICE) FROM ORDERS
GROUP BY PRODUCT;
SELECT PRODUCT,MAX(PRICE) FROM ORDERS
GROUP BY PRODUCT;
SELECT PRODUCT,AVG(PRICE) FROM ORDERS
GROUP BY PRODUCT; 

SELECT PRODUCT,SUM(PRICE*QUANTITY) FROM ORDERS
GROUP BY PRODUCT;
SELECT CITY,SUM(PRICE*QUANTITY) FROM ORDERS
GROUP BY CITY;
SELECT CITY,SUM(QUANTITY) FROM ORDERS
WHERE PRODUCT = "LAPTOP"
GROUP BY CITY;
SELECT PRODUCT,AVG(QUANTITY) FROM ORDERS
GROUP BY PRODUCT;
 