CREATE DATABASE SAMPLE23;
USE SAMPLE23;


CREATE TABLE EMPLOYEES(
	EMP_ID INT PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    DEPARTMENT VARCHAR(20) NOT NULL,
    SALARY INT NOT NULL DEFAULT 0,
    AGE INT NOT NULL,
    CITY VARCHAR(20) NOT NULL
);
INSERT INTO employees (emp_id, name, department, salary, age, city) VALUES
(1, 'Alice',   'HR',        40000, 28, 'Delhi'),
(2, 'Bob',     'IT',        60000, 32, 'Mumbai'),
(3, 'Charlie', 'Finance',   55000, 29, 'Bangalore'),
(4, 'Diana',   'IT',        62000, 35, 'Mumbai'),
(5, 'Eve',     'HR',        42000, 26, 'Chennai'),
(6, 'Frank',   'Finance',   40000, 31, 'Delhi'),
(7, 'Grace',   'IT',        58000, 30, 'Hyderabad');
SELECT * FROM EMPLOYEES;

-- MULTI ROW

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT IN (
	SELECT DEPARTMENT FROM EMPLOYEES
	WHERE CITY = "DELHI"
);
SELECT * FROM EMPLOYEES
WHERE SALARY IN (
	SELECT SALARY FROM EMPLOYEES
	WHERE DEPARTMENT = "HR"
);
SELECT * FROM EMPLOYEES
WHERE CITY IN (
	SELECT CITY FROM EMPLOYEES
	WHERE DEPARTMENT = "IT"
);

SELECT * FROM EMPLOYEES
WHERE SALARY > ANY (
	SELECT SALARY FROM EMPLOYEES
	WHERE DEPARTMENT = "HR"
);

SELECT * FROM EMPLOYEES
WHERE AGE > ANY (
	SELECT AGE FROM EMPLOYEES
	WHERE DEPARTMENT = "FINANCE"
);
SELECT * FROM EMPLOYEES
WHERE SALARY < ANY (
	SELECT SALARY FROM EMPLOYEES
	WHERE CITY = "MUMBAI"
);
SELECT * FROM EMPLOYEES
WHERE SALARY > ALL (
	SELECT SALARY FROM EMPLOYEES
	WHERE DEPARTMENT = "HR"
);
SELECT * FROM EMPLOYEES
WHERE AGE < ALL (
	SELECT AGE FROM EMPLOYEES
	WHERE DEPARTMENT = "IT"
);
SELECT * FROM EMPLOYEES
WHERE SALARY <= ALL (
	SELECT SALARY FROM EMPLOYEES
	WHERE DEPARTMENT = "FINANCE"
);


SELECT * FROM EMPLOYEES E1
WHERE SALARY > (
	SELECT AVG(SALARY) FROM EMPLOYEES E2
    WHERE E1.DEPARTMENT = E2.DEPARTMENT
);

SELECT * FROM EMPLOYEES AS E1
WHERE AGE > (
	SELECT AVG(AGE) FROM EMPLOYEES AS E2
    WHERE E2.CITY = E1.CITY 
);

SELECT * FROM EMPLOYEES AS E1
WHERE SALARY >= (
	SELECT MAX(SALARY) FROM EMPLOYEES E2
    WHERE E1.DEPARTMENT = E2.DEPARTMENT
);

SELECT * FROM EMPLOYEES E1
WHERE AGE <= (
	SELECT MIN(AGE) FROM EMPLOYEES E2
    WHERE E2.DEPARTMENT = E1.DEPARTMENT 
);

SELECT * FROM EMPLOYEES AS E1
WHERE SALARY <= (
	SELECT MIN(SALARY) FROM EMPLOYEES AS E2
    WHERE E1.CITY = E2.CITY
);

SELECT * FROM EMPLOYEES E1
WHERE SALARY > ANY (
	SELECT SALARY FROM EMPLOYEES E2
    WHERE E2.DEPARTMENT = E1.DEPARTMENT
);

SELECT * FROM EMPLOYEES E1
WHERE SALARY >= (
	SELECT SALARY FROM EMPLOYEES E2
    WHERE E2.AGE = E1.AGE
);
SELECT * FROM EMPLOYEES E1
WHERE 2 < (
	SELECT COUNT(*) FROM EMPLOYEES E2
	WHERE E2.DEPARTMENT = E1.DEPARTMENT
);



