CREATE DATABASE SAMPLE11;
USE SAMPLE11;

CREATE TABLE STUDENTSCORE(
	ID INT,
    NAME VARCHAR(20),
    SUBJECT VARCHAR(10),
    MARKS INT
);
INSERT INTO StudentScore VALUES
(1, 'Alice', 'Math', 95),
(2, 'Bob', 'Math', 76),
(3, 'Charlie', 'Math', 59),
(4, 'Diana', 'Math', 88),
(5, 'Eve', 'Math', 40),
(6, 'Frank', 'Math', 95);
SELECT * FROM STUDENTSCORE;

SELECT * FROM STUDENTSCORE WHERE MARKS > 90;
SELECT * FROM STUDENTSCORE
WHERE MARKS >= 60;
SELECT * FROM STUDENTSCOR
WHERE MARKS < 50;
SELECT * FROM STUDENTSCORE
WHERE MARKS = 95;
SELECT * FROM STUDENTSCORE
WHERE MARKS != 95;
SELECT * FROM STUDENTSCORE
WHERE MARKS <= 60; 

SET SQL_SAFE_UPDATES = 0;
UPDATE STUDENTSCORE SET MARKS = MARKS + 10
WHERE MARKS < 50;
SELECT * FROM STUDENTSCORE;

UPDATE STUDENTSCORE SET MARKS = MARKS + 5
WHERE MARKS <= 60;
SELECT * FROM STUDENTSCORE;

SELECT * FROM STUDENTSCORE WHERE MARKS > 90;
UPDATE STUDENTSCORE SET MARKS = MARKS + 2
WHERE MARKS > 90; 
SELECT * FROM STUDENTSCORE;

SELECT * FROM STUDENTSCORE WHERE MARKS >= 80;
UPDATE STUDENTSCORE SET MARKS = MARKS + 3 
WHERE MARKS >= 80;
SELECT * FROM STUDENTSCORE;

SELECT * FROM STUDENTSCORE WHERE MARKS != 95;
UPDATE STUDENTSCORE SET MARKS = MARKS - 1
WHERE MARKS != 95;
SELECT * FROM STUDENTSCORE;

UPDATE STUDENTSCORE SET MARKS = 100
WHERE MARKS = 99;
SELECT * FROM STUDENTSCORE;

SELECT * FROM STUDENTSCORE WHERE MARKS < 60;
DELETE FROM STUDENTSCORE
WHERE MARKS < 60;
SELECT * FROM STUDENTSCORE; 

DELETE FROM STUDENTSCORE
WHERE MARKS <= 60;
SELECT * FROM STUDENTSCORE;

SELECT * FROM STUDENTSCORE WHERE MARKS > 90;
DELETE FROM STUDENTSCORE
WHERE MARKS > 90;
SELECT * FROM STUDENTSCORE;

SELECT * FROM STUDENTSCORE WHERE MARKS >= 80;
DELETE FROM STUDENTSCORE
WHERE MARKS >= 80;
SELECT * FROM STUDENTSCORE;

DELETE FROM STUDENTSCORE
WHERE MARKS != 95;

DELETE FROM STUDENTSCORE
WHERE MARKS = 76;
SELECT * FROM STUDENTSCORE;


CREATE TABLE EMPLOYEES(
	ID INT,
    NAME VARCHAR(20),
    DEPARTMENT VARCHAR(10),
    SALARY FLOAT,
    ISACTIVE BOOL
);
INSERT INTO EMPLOYEES VALUES 
(1,"ALICE","IT",30000,TRUE),
(2,"BOB","IT",35000,TRUE),
(3,"JOHN","HR",30000,FALSE),
(4,"JACK","FINANCE",45000,TRUE),
(5,"EVE","FINANCE",40000,FALSE);

SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT = "IT" AND SALARY > 30000;

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT = "HR" OR SALARY < 35000;

SELECT * FROM EMPLOYEES
WHERE NOT DEPARTMENT = "HR";

SELECT * FROM EMPLOYEES
WHERE (DEPARTMENT = "FINANCE" OR SALARY > 30000) AND ISACTIVE = TRUE;

SELECT * FROM EMPLOYEES
WHERE SALARY < 60000 AND DEPARTMENT = "IT" AND ISACTIVE = TRUE;

UPDATE EMPLOYEES SET SALARY = SALARY + 2000
WHERE SALARY < 60000 AND DEPARTMENT = "IT" AND ISACTIVE = TRUE;
SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT = "FINANCE" OR ISACTIVE = FALSE;

UPDATE EMPLOYEES SET SALARY = SALARY - SALARY * 0.10
WHERE DEPARTMENT = "FINANCE" OR ISACTIVE = FALSE;

UPDATE EMPLOYEES SET ISACTIVE = FALSE
WHERE NOT DEPARTMENT = "IT";

SELECT * FROM EMPLOYEES; 

DELETE FROM EMPLOYEES
WHERE DEPARTMENT = "HR" OR ISACTIVE = FALSE;
SELECT * FROM EMPLOYEES;

DELETE FROM EMPLOYEES
WHERE DEPARTMENT = "FINANCE" OR SALARY < 35000;
SELECT * FROM EMPLOYEES;

DELETE FROM EMPLOYEES
WHERE NOT DEPARTMENT = "IT";