CREATE DATABASE SAMPLE15;
USE SAMPLE15;

CREATE TABLE EMPLOYEES(
	EMP_ID INT PRIMARY KEY,
    FIRSTNAME VARCHAR(20) NOT NULL,
    LASTNAME VARCHAR(20),
    EMAIL VARCHAR(20),
    DEPARMTNENT VARCHAR(20),
    SALARY INT CHECK (SALARY > 0),
    DOJ DATE
);
INSERT INTO EmployeeS VALUES 
(101, 'Alice', 'Johnson', 'alice.j@gmail.com', 'HR', 55000.00, '2022-03-01'),
(102, 'Bob', 'Smith', 'bob.smith@gmail.com', 'Sales', 60000.00, '2023-07-15'),
(103, 'Charlie', NULL, 'charlie.c@gmail.com', 'IT', 70000.00, '2021-11-20'),
(104, 'Diana', 'Stone', 'diana.s@gmail.com', 'HR', 58000.00, '2024-01-10'),
(105, 'Ethan', 'Miles', 'ethan.m@gmail.com', 'Finance', 49000.00, '2023-05-05');
SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE DEPARMTNENT = "HR";

SET SQL_SAFE_UPDATES = 0;
UPDATE EMPLOYEES SET SALARY = SALARY + SALARY * 0.10
WHERE DEPARMTNENT = "HR";

ALTER TABLE EMPLOYEES
CHANGE DEPARMTNENT DEPARTMENT VARCHAR(20);

SELECT * FROM EMPLOYEES;

UPDATE EMPLOYEES 
SET DEPARTMENT = "Human Resourses"
WHERE DEPARTMENT = "HR";

SELECT * FROM EMPLOYEES;

ALTER TABLE EMPLOYEES
ADD COLUMN PHONE VARCHAR(15);
SELECT * FROM EMPLOYEES;

ALTER TABLE EMPLOYEES
MODIFY COLUMN DEPARTMENT VARCHAR(100);
DESCRIBE EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE SALARY > 50000;

SELECT * FROM EMPLOYEES
WHERE DOJ > "2023-01-01";

SELECT * FROM EMPLOYEES
WHERE FIRSTNAME LIKE "A%";

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT = "SALES" OR DEPARTMENT = "IT";

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT IN ("SALES","IT");

SELECT CONCAT(FIRSTNAME," ",LASTNAME) AS FULLNAME
FROM EMPLOYEES;

SELECT FIRSTNAME,LENGTH(FIRSTNAME) FROM EMPLOYEES;
SELECT FIRSTNAME,CHAR_LENGTH(FIRSTNAME) FROM EMPLOYEES;

SELECT FIRSTNAME,UPPER(LASTNAME) FROM EMPLOYEES;
SELECT * FROM EMPLOYEES;
UPDATE EMPLOYEES SET LASTNAME = UPPER(LASTNAME);
SELECT * FROM EMPLOYEES;

SELECT FIRSTNAME,SUBSTRING(FIRSTNAME,1,3) FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE SALARY BETWEEN 40000 AND 80000;

SELECT * FROM EMPLOYEES
WHERE SALARY > 40000 AND SALARY < 80000;

SELECT * FROM EMPLOYEES
WHERE EMAIL LIKE "%@GMAIL.COM";

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT != "FINANCE";

SELECT * FROM EMPLOYEES
WHERE NOT DEPARTMENT = "FINANCE";

SELECT * FROM EMPLOYEES
WHERE FIRSTNAME = "JOHN" AND DEPARTMENT="SALES";

SELECT * FROM EMPLOYEES
WHERE LASTNAME IS NULL;

SELECT * FROM EMPLOYEES 
WHERE SALARY < 50000;

UPDATE EMPLOYEES
SET SALARY = SALARY + 5000
WHERE SALARY < 50000;
SELECT * FROM EMPLOYEES;

DELETE FROM EMPLOYEES
WHERE EMP_ID = 105;

SELECT * FROM EMPLOYEES;

ALTER TABLE EMPLOYEES
CHANGE PHONE MOBILENUMBER VARCHAR(15);

SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE FIRSTNAME LIKE "%E%";

SELECT * FROM EMPLOYEES
WHERE LASTNAME LIKE "%N";


SELECT * FROM EMPLOYEES
WHERE NOT EMAIL LIKE "%@GMAIL.COM";

SELECT FIRSTNAME,DEPARTMENT,LENGTH(DEPARTMENT)
FROM EMPLOYEES;