CREATE DATABASE SAMPLE22;
USE SAMPLE22;

CREATE TABLE EMPLOYEES(
	EMP_ID INT PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    DEPARTMENT VARCHAR(20) NOT NULL,
    SALARY INT NOT NULL DEFAULT 0,
    AGE INT NOT NULL,
    CITY VARCHAR(20) NOT NULL
);
INSERT INTO employees VALUES
(1, 'Alice',   'HR',        40000, 28, 'Delhi'),
(2, 'Bob',     'IT',        60000, 32, 'Mumbai'),
(3, 'Charlie', 'Finance',   55000, 29, 'Bangalore'),
(4, 'Diana',   'IT',        62000, 35, 'Mumbai'),
(5, 'Eve',     'HR',        42000, 26, 'Chennai'),
(6, 'Frank',   'Finance',   53000, 31, 'Delhi'),
(7, 'Grace',   'IT',        58000, 30, 'Hyderabad');
SELECT * FROM EMPLOYEES;

SELECT AVG(SALARY) FROM EMPLOYEES;

SELECT NAME,
	(SELECT AVG(SALARY) FROM EMPLOYEES) AS AVG_SALARY
FROM EMPLOYEES; 
SELECT NAME,SALARY,
	(SELECT MAX(SALARY) FROM EMPLOYEES)-SALARY AS DIFF_SALARY
FROM EMPLOYEES;
SELECT NAME,SALARY,
	SALARY - (SELECT AVG(SALARY) FROM EMPLOYEES) AS DIFFERENCE_SALARY
FROM EMPLOYEES;

-- SELECT AVG(SALARY) FROM EMPLOYEES;
SELECT * FROM EMPLOYEES
WHERE SALARY > (
	SELECT AVG(SALARY) FROM EMPLOYEES
);
-- SELECT MIN(SALARY) FROM EMPLOYEES
-- WHERE DEPARTMENT = "FINANCE";
SELECT * FROM EMPLOYEES
WHERE SALARY > (
	SELECT MIN(SALARY) FROM EMPLOYEES
	WHERE DEPARTMENT = "FINANCE"
);
-- SELECT CITY FROM EMPLOYEES
-- WHERE EMP_ID = 1;
SELECT * FROM EMPLOYEES
WHERE CITY = ( 
	SELECT CITY FROM EMPLOYEES
	WHERE EMP_ID = 1
);

SELECT * FROM EMPLOYEES
WHERE AGE < (
	SELECT MAX(AGE) FROM EMPLOYEES
    WHERE DEPARTMENT = "IT"
);
SELECT * FROM EMPLOYEES
WHERE SALARY > (
	SELECT SALARY FROM EMPLOYEES
    WHERE NAME = "EVE"
); 

SELECT * FROM EMPLOYEES
WHERE SALARY > (
	SELECT AVG(SALARY) FROM EMPLOYEES
);

SELECT * FROM EMPLOYEES
WHERE CITY = (
	SELECT CITY FROM EMPLOYEES
    WHERE EMP_ID = 5
);

SELECT * FROM EMPLOYEES
WHERE AGE > (
	SELECT MIN(AGE) FROM EMPLOYEES
	WHERE DEPARTMENT = "FINANCE"
);

SELECT * FROM EMPLOYEES
WHERE SALARY = (
	SELECT MAX(SALARY) FROM EMPLOYEES
	WHERE DEPARTMENT = "HR"
);
SELECT * FROM EMPLOYEES
WHERE SALARY < (
	SELECT SALARY FROM EMPLOYEES
	WHERE NAME = "DIANA" 
);

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT = (
	SELECT DEPARTMENT FROM EMPLOYEES
	WHERE NAME = "CHARLIE"
);

SELECT * FROM EMPLOYEES
WHERE CITY = (
	SELECT CITY FROM EMPLOYEES
	WHERE SALARY = (
		SELECT MIN(SALARY) FROM EMPLOYEES
	)
);

SELECT * FROM EMPLOYEES
WHERE AGE > (
	SELECT AVG(AGE) FROM EMPLOYEES
	WHERE DEPARTMENT = "IT"
);
SELECT * FROM EMPLOYEES
WHERE SALARY = (
	SELECT MIN(SALARY) FROM EMPLOYEES
);

SELECT * FROM EMPLOYEES
WHERE AGE = (
	SELECT MAX(AGE) FROM EMPLOYEES
);



