CREATE DATABASE SAMPLE17;
USE SAMPLE17;

CREATE TABLE EMPLOYEES(
	EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(20) NOT NULL,
    EMP_SALARY INT NOT NULL DEFAULT 1000
);

CREATE TABLE DEPARTMENTS(
	DEPT_ID INT,
    DEPT_NAME VARCHAR(20)
);
CREATE TABLE EMP(
	EMP_ID INT,
    EMP_NAME VARCHAR(20),
    DEPT_ID INT
);

DESCRIBE DEPARTMENTS;
ALTER TABLE DEPARTMENTS
ADD PRIMARY KEY (DEPT_ID);
DESCRIBE DEPARTMENTS;

DESCRIBE EMP;
ALTER TABLE EMP
ADD PRIMARY KEY (EMP_ID);
DESCRIBE EMP;

DESCRIBE EMP;
ALTER TABLE EMP
ADD UNIQUE (EMP_NAME);
DESCRIBE EMP;

ALTER TABLE EMP
ADD CONSTRAINT FK_DEPT_ID
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID);
DESCRIBE EMP;

ALTER TABLE EMP
MODIFY EMP_NAME VARCHAR(20) NOT NULL;
DESCRIBE EMP;

DESCRIBE EMP;
ALTER TABLE EMP
DROP PRIMARY KEY;
DESCRIBE EMP;

ALTER TABLE EMP
DROP INDEX EMP_NAME;
DESCRIBE EMP;

ALTER TABLE EMP
DROP FOREIGN KEY FK_DEPT_ID;
DESCRIBE EMP;

ALTER TABLE DEPARTMENTS
DROP PRIMARY KEY;
DESCRIBE DEPARTMENTS;

