CREATE DATABASE HELLO80;
USE HELLO80;

CREATE TABLE EMPLOYEES(
	EMP_ID INT,
    EMP_NAME VARCHAR(100),
    EMP_EMAIL VARCHAR(150),
    EMP_SALARY INT
);
INSERT INTO employees (emp_id, emp_name, emp_email, emp_salary) VALUES
(1, 'John Doe', 'john@example.com', 50000.00),
(2, 'Jane Smith', 'jane@example.com', 60000.00),
(3, 'Alice Brown', 'alice@example.com', 55000.00);
SELECT * FROM EMPLOYEES;

ALTER TABLE EMPLOYEES ADD EMP_PHONE VARCHAR(15);
SELECT * FROM EMPLOYEES;

ALTER TABLE EMPLOYEES ADD DATE_OF_JOINING DATE;
SELECT * FROM EMPLOYEES;

ALTER TABLE EMPLOYEES ADD DEPARTMENT VARCHAR(50);
SELECT * FROM EMPLOYEES;

ALTER TABLE EMPLOYEES DROP COLUMN EMP_EMAIL;
SELECT * FROM EMPLOYEES;

ALTER TABLE EMPLOYEES DROP COLUMN DEPARTMENT;
SELECT * FROM EMPLOYEES;

ALTER TABLE EMPLOYEES DROP DATE_OF_JOINING;
SELECT * FROM EMPLOYEES;

ALTER TABLE EMPLOYEES
MODIFY EMP_SALARY DECIMAL(12,2);
SELECT * FROM EMPLOYEES;

DESCRIBE EMPLOYEES;
ALTER TABLE EMPLOYEES
MODIFY EMP_NAME VARCHAR(150);
DESCRIBE EMPLOYEES;

ALTER TABLE EMPLOYEES
CHANGE EMP_NAME EMPLOYEE_NAME VARCHAR(150);
SELECT * FROM EMPLOYEES;
DESCRIBE EMPLOYEES;

ALTER TABLE EMPLOYEES
CHANGE EMP_SALARY SALARY FLOAT;
DESCRIBE EMPLOYEES;
SELECT * FROM EMPLOYEES;

ALTER TABLE EMPLOYEES
CHANGE EMP_PHONE MOBILE_NUMBER VARCHAR(20);
SELECT * FROM EMPLOYEES;
DESCRIBE EMPLOYEES;

RENAME TABLE EMPLOYEES TO STAFF;
SELECT * FROM STAFF;
SELECT * FROM EMPLOYEES;

RENAME TABLE STAFF TO EMPLOYEES;

RENAME TABLE EMPLOYEES TO COMPANY_EMPLOYEES1;
SELECT * FROM EMPLOYEES;
SELECT * FROM COMPANY_EMPLOYEES1;