CREATE DATABASE DB24;
USE DB24;

CREATE TABLE SALES(
	SALE_ID INT PRIMARY KEY,
    PRODUCT VARCHAR(20),
    CATEGORY VARCHAR(20),
    UNITS_SOLD INT,
    UNIT_PRICE INT,
    REGION VARCHAR(20)
);
INSERT INTO sales (sale_id, product, category, units_sold, unit_price, region) VALUES
(1, 'Keyboard',    'Electronics', 10, 1200,  'North'),
(2, 'Monitor',     'Electronics', 5,  7000,  'South'),
(3, 'Chair',       'Furniture',   15, 2500,  'North'),
(4, 'Desk',        'Furniture',   7,  4500,  'West'),
(5, 'Mouse',       'Electronics', 20, 800,   'East'),
(6, 'Sofa',        'Furniture',   3,  15000, 'South'),
(7, 'Headphones',  'Electronics', 8,  1800,  'North');
SELECT * FROM  SALES;

-- HAVING

SELECT CATEGORY,SUM(UNITS_SOLD)
FROM SALES
GROUP BY CATEGORY
HAVING SUM(UNITS_SOLD) > 25;

SELECT CATEGORY,SUM(UNITS_SOLD) AS TOTAL
FROM SALES
GROUP BY CATEGORY
HAVING TOTAL > 25;

SELECT REGION,SUM(UNITS_SOLD * UNIT_PRICE) REVENUE
FROM SALES
GROUP BY REGION
HAVING REVENUE > 50000;

SELECT CATEGORY,SUM(UNITS_SOLD) AS TOTAL_SOLD
FROM SALES
GROUP BY CATEGORY
HAVING TOTAL_SOLD > 13;

SELECT CATEGORY,AVG(UNIT_PRICE)
FROM SALES
GROUP BY CATEGORY
HAVING AVG(UNIT_PRICE) < 5000;


SELECT REGION,COUNT(*)
FROM SALES
WHERE CATEGORY = "ELECTRONICS"
GROUP BY REGION
HAVING COUNT(*) > 1;

-- ORDER BY
SELECT CATEGORY,SUM(UNITS_SOLD)
FROM SALES
GROUP BY CATEGORY
ORDER BY SUM(UNITS_SOLD);

SELECT REGION,AVG(UNIT_PRICE)
FROM SALES
GROUP BY REGION
ORDER BY REGION ASC;

SELECT CATEGORY,SUM(UNITS_SOLD * UNIT_PRICE) AS REVENUE
FROM SALES
GROUP BY CATEGORY
ORDER BY REVENUE DESC;

SELECT REGION,COUNT(PRODUCT)
FROM SALES
GROUP BY REGION
ORDER BY COUNT(PRODUCT) DESC;

SELECT REGION,SUM(UNITS_SOLD)
FROM SALES
GROUP BY REGION
ORDER BY REGION; 


-- HAVING & ORDER BY

SELECT REGION,SUM(UNITS_SOLD * UNIT_PRICE) AS REVENUE
FROM SALES
GROUP BY REGION
HAVING REVENUE > 20000
ORDER BY REVENUE DESC;

SELECT CATEGORY,SUM(UNITS_SOLD)
FROM SALES
GROUP BY CATEGORY
HAVING SUM(UNITS_SOLD) > 10
ORDER BY CATEGORY;

SELECT REGION,COUNT(*)
FROM SALES
GROUP BY REGION
HAVING COUNT(*) > 1
ORDER BY REGION;

SELECT CATEGORY,AVG(UNIT_PRICE)
FROM SALES
GROUP BY CATEGORY
HAVING AVG(UNIT_PRICE) < 6000
ORDER BY AVG(UNIT_PRICE);

SELECT CATEGORY,AVG(UNITS_SOLD)
FROM SALES 
GROUP BY CATEGORY
HAVING AVG(UNITS_SOLD) > 5
ORDER BY AVG(UNITS_SOLD) DESC;

CREATE TABLE EMPLOYEES(
	EMP_ID INT PRIMARY KEY,
	NAME VARCHAR(30) NOT NULL,
    DEPARTMENT VARCHAR(20) NOT NULL,
    SALARY INT NOT NULL DEFAULT 0,
    AGE INT NOT NULL,
    CITY VARCHAR(20) NOT NULL
);
INSERT INTO employees (emp_id, name, department, salary, age, city) VALUES
(1, 'Alice',   'HR',        40000, 28, 'Delhi'),
(2, 'Bob',     'IT',        60000, 32, 'Mumbai'),
(3, 'Charlie', 'Finance',   55000, 29, 'Bangalore'),
(4, 'Diana',   'IT',        62000, 35, 'Mumbai'),
(5, 'Eve',     'HR',        42000, 26, 'Chennai'),
(6, 'Frank',   'Finance',   53000, 31, 'Delhi'),
(7, 'Grace',   'IT',        58000, 30, 'Hyderabad');
SELECT * FROM EMPLOYEES;


SELECT DEPARTMENT,AVG(SALARY)
FROM  EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY AVG(SALARY) DESC
LIMIT 1;

SELECT department, avg_salary
FROM (
    SELECT department, AVG(salary) AS avg_salary
    FROM employees
    GROUP BY department
) AS dept_avg
ORDER BY avg_salary DESC
LIMIT 1;


SELECT DEPARTMENT,SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING SUM(SALARY) > (
	SELECT SUM(SALARY)
	FROM EMPLOYEES
	WHERE DEPARTMENT = "HR" 
);