CREATE DATABASE SAMPLE18;
USE SAMPLE18;

CREATE TABLE EMPLOYEES(
	EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(20) NOT NULL,
    EMP_SALARY INT NOT NULL DEFAULT 1000
);

CREATE USER "ADMIN1" IDENTIFIED BY "1234";

CREATE USER "ADMIN2" IDENTIFIED BY "5678";

GRANT INSERT ON EMPLOYEES TO ADMIN1;
GRANT SELECT ON EMPLOYEES TO ADMIN1;

GRANT UPDATE ON EMPLOYEES TO ADMIN2;
GRANT SELECT ON EMPLOYEES TO ADMIN2;


SELECT * FROM EMPLOYEES;


REVOKE INSERT ON EMPLOYEES FROM ADMIN1;
REVOKE UPDATE ON EMPLOYEES FROM ADMIN2;