CREATE DATABASE SAMPLE20;
USE SAMPLE20;

CREATE TABLE STUDENTS(
	STUDENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    STUDENT_NAME VARCHAR(20) NOT NULL,
    STUDENT_MARKS INT NOT NULL DEFAULT 0,
    STUDENT_BRANCH VARCHAR(20) NOT NULL
);

CREATE USER "MANAGER1001" IDENTIFIED BY "1234";
CREATE USER "MANAGER2002" IDENTIFIED BY "5678";

GRANT INSERT ON STUDENTS TO MANAGER1001;
GRANT SELECT ON STUDENTS TO MANAGER1001;
GRANT UPDATE ON STUDENTS TO MANAGER1001;

GRANT SELECT ON STUDENTS TO MANAGER2002;
GRANT UPDATE ON STUDENTS TO MANAGER2002;
GRANT DELETE ON STUDENTS TO MANAGER2002;


REVOKE UPDATE ON STUDENTS FROM MANAGER1001;


GRANT DELETE ON STUDENTS TO MANAGER1001;

GRANT INSERT ON STUDENTS TO MANAGER2002;