CREATE DATABASE SAMPLE10;
USE SAMPLE10;

CREATE TABLE EMPLOYEES(
	EMP_ID INT,
    EMP_NAME VARCHAR(20),
    EMP_SALARY INT,
    EMP_DEPARTMENT VARCHAR(10)
);
INSERT INTO EMPLOYEES VALUES (101,"E1",20000,"HR");
SELECT * FROM EMPLOYEES;
INSERT INTO EMPLOYEES (EMP_NAME,EMP_ID,EMP_SALARY,EMP_DEPARTMENT) VALUES 
("E2",102,45000,"IT");
SELECT * FROM EMPLOYEES;
INSERT INTO EMPLOYEES VALUES (103,"E3",40000,"HR");
INSERT INTO EMPLOYYES VALUES (104,"E4",50000,"IT");
SELECT * FROM EMPLOYEES;
INSERT INTO EMPLOYEES VALUE 
(105,"E5",30000,"FINANCE"),
(106,"E6",60000,"IT"),
(107,"E7",70000,"IT");
SELECT * FROM EMPLOYEES;

INSERT INTO EMPLOYEES (EMP_SALARY,EMP_ID,EMP_NAME,EMP_DEPARTMENT) VALUES 
(50000,108,"E8","HR"),
(75000,109,"E9","FINANCE");
SELECT * FROM EMPLOYEES;

INSERT INTO EMPLOYEES (EMP_ID,EMP_NAME) VALUES (110,"E10");
SELECT * FROM EMPLOYEES;
INSERT INTO EMPLOYEES (EMP_NAME,EMP_DEPARTMENT) VALUES ("E11","HR");
SELECT * FROM EMPLOYEES;
INSERT INTO EMPLOYEES (EMP_ID,EMP_SALARY) VALUES 
(112,30000),
(113,45000),
(114,78000);
SELECT * FROM EMPLOYEES;

CREATE TABLE NEW_EMPLOYEES(
	EMP_ID INT,
    EMP_NAME VARCHAR(20)
);
SELECT * FROM NEW_EMPLOYEES;
INSERT INTO NEW_EMPLOYEES (EMP_ID,EMP_NAME)
SELECT EMP_ID,EMP_NAME FROM EMPLOYEES;
SELECT * FROM NEW_EMPLOYEES;

CREATE TABLE TABLE1(
	COL1 INT,
    COL2 VARCHAR(20)
);
INSERT INTO TABLE1 (COL1,COL2)
SELECT EMP_ID,EMP_NAME FROM EMPLOYEES;
SELECT * FROM TABLE1;

SELECT * FROM NEW_EMPLOYEES;

SET SQL_SAFE_UPDATES = 0;
UPDATE NEW_EMPLOYEES SET EMP_NAME = "HELLO";
SELECT * FROM NEW_EMPLOYEES;

SELECT * FROM EMPLOYEES;
UPDATE EMPLOYEES SET EMP_SALARY = 100000 WHERE EMP_DEPARTMENT = "IT";
SELECT * FROM EMPLOYEES;

SELECT * FROM NEW_EMPLOYEES;

SELECT * FROM TABLE1;
DROP TABLE TABLE1;
SELECT * FROM TABLE1;

TRUNCATE NEW_EMPLOYEES;
SELECT * FROM NEW_EMPLOYEES;

DELETE FROM EMPLOYEES WHERE EMP_DEPARTMENT = "FINANCE";
SELECT * FROM EMPLOYEES;

DELETE FROM EMPLOYEES;
SELECT * FROM EMPLOYEES;