CREATE DATABASE DB3;
USE DB3;

CREATE TABLE TABLE1(
	COL1 CHAR(5),
    COL2 VARCHAR(5)
);
INSERT INTO TABLE1 VALUES ("A","A");
SELECT * FROM TABLE1;
INSERT INTO TABLE1 VALUES ("ABCDE","ABCDE");
SELECT * FROM TABLE1;
INSERT INTO TABLE1 VALUES ("ABCDEFG","ABCDEFG");


CREATE TABLE TABLE3(
	COL1 BINARY(5),
    COL2 VARBINARY(5),
    COL3 CHAR(5),
    COL4 VARCHAR(5)
);
INSERT INTO TABLE3 VALUES ("A","A","A","A");
SELECT * FROM TABLE3;

CREATE TABLE TABLE4(
	COL1 BLOB,
    COL2 LONGBLOB
);
INSERT INTO TABLE4 VALUES ("HELLO","HELLO");
SELECT * FROM TABLE4;

CREATE TABLE TABLE5(
	COL1 TINYTEXT,
    COL2 MEDIUMTEXT,
    COL3 LONGTEXT,
    COL4 TEXT
);
INSERT INTO TABLE5 VALUES ("ABCDASDFGHJKJHGFDFGHJKJHGFDFGHJKLKJHGFDABCDASDFGHJKJHGFDFGHJKJHGFDFGHJKLKJHGFABCDASDFGHJKJHGFDFGHJKJHGFDFGHJKLKJHGFABABCDASDFGHJKJHGFDFGHJKJHGFDFGHJKLKJHGFABCDASDFGHJKJHGFDFGHJKJHGFDFGHJKLKJHGFABCDASDFGHJKJHGFDFGHJKJHGFDFGHJKLKJHGFABCDASDFGHJKJHGFDFGHJKJHGFDFGHJKLKJHGFABCDASDFGHJKJHGFDFGHJKJHGFDFGHJKLKJHGFCDASDFGHJKJHGFDFGHJKJHGFDFGHJKLKJHGF","ABCD","ABCD","ABCD");
SELECT * FROM TABLE5;

CREATE TABLE TABLE6(
	COL1 ENUM("MALE","FEMALE","OTHERS")
);
INSERT INTO TABLE6 VALUES ("MALE");
SELECT * FROM TABLE6;
INSERT INTO TABLE6 VALUES ("male");
SELECT * FROM TABLE6;
INSERT INTO TABLE6 VALUES ("FEMALE");
SELECT * FROM TABLE6;
INSERT INTO TABLE6 VALUES ("OTHERS");
SELECT * FROM TABLE6;
INSERT INTO TABLE6 VALUES ("HELLO");
SELECT * FROM TABLE6;
INSERT INTO TABLE6 VALUES ("MALE,FEMALE");
SELECT * FROM TABLE6;


CREATE TABLE TABLE7(
	COL1 SET("READING","WRITING","SINGING")
);
INSERT INTO TABLE7 VALUES ("READING");
SELECT * FROM TABLE7;
INSERT INTO TABLE7 VALUES ("reading");
SELECT * FROM TABLE7;
INSERT INTO TABLE7 VALUES ("writing");
SELECT * FROM TABLE7;
INSERT INTO TABLE7 VALUES ("SINGING");
SELECT * FROM TABLE7;
INSERT INTO TABLE7 VALUES ("HELLO");
SELECT * FROM TABLE7;
INSERT INTO TABLE7 VALUES ("READING,WRITING");
SELECT * FROM TABLE7;
INSERT INTO TABLE7 VALUES ("READING,SINGING");
SELECT * FROM TABLE7;
INSERT INTO TABLE7 VALUES ("READING,SLEEPING");
SELECT * FROM TABLE7;

CREATE TABLE TABLE8(
	GENDER ENUM("FEMLAE","MALE","OTHERS"),
    HOBBIES SET("SLEEPING","SINGING","READING","WRITING")
);
INSERT INTO TABLE8 VALUES ("MALE","SLEEPING");
SELECT * FROM TABLE8;
INSERT INTO TABLE8 VALUES ("FEMLAE","SLEEPING,WRITING");
SELECT * FROM TABLE8;